unit Defines;

interface

const
  Nulled: AnsiString = '';

var
  MultiplierExp: UInt8 = 1;
  MultiplierRain: UInt8 = 1;

type
  TCLUB_STATUS = (
    csPower = $0,
    csControl,
    csImpact,
    csSpin,
    csCurve
  );

  TCLUB_TYPE = (
    CLUB_TYPE_1W = 0,
    CLUB_TYPE_2W,
    CLUB_TYPE_3W,
    CLUB_TYPE_2L,
    CLUB_TYPE_3L,
    CLUB_TYPE_4L,
    CLUB_TYPE_5L,
    CLUB_TYPE_6L,
    CLUB_TYPE_7L,
    CLUB_TYPE_8L,
    CLUB_TYPE_9L,
    CLUB_TYPE_PW,
    CLUB_TYPE_SW,
    CLUB_TYPE_PT1,
    CLUB_TYPE_PT2
);

  TGET_CLUB = (
    gcTypeID,
    gcIndex
  );

  TTEAM_VERSUS = (
    tvRed = $0,
    tvBlue = $1
  );

  TPOWER_SHOT = (
    NO_POWERSHOT = $0,
    POWERSHOT = $1,
    DOUBLE_P_POWERSHOT = $2,
    DOUBLE_POWERSHOT = $3
  );

  TPLAYER_CHATROOM_ACTION = (
    PLAYER_WALK = $6,
    PLAYER_APPEAR = $4
  );

  TPACKCARD = (
    Pack1,
    Pack2,
    Pack3,
    Pack4,
    Rare,
    All
  );

  TPLAYER_ACTION = (
      PLAYER_ACTION_NULL = $00,
      PLAYER_ACTION_APPEAR = $04,
      PLAYER_ACTION_SUB = $05,
      PLAYER_ACTION_MOVE = $06,
      PLAYER_ACTION_ANIMATION = $07,
      PLAYER_ACTION_HEADER = $08
    );

  TITEMGROUP = (
    ITEM_TYPE_CHARACTER = $1,
    ITEM_TYPE_PART = $2,
    ITEM_TYPE_CLUB = $4,
    ITEM_TYPE_BALL = $5,
    ITEM_TYPE_USE = $6,
    ITEM_TYPE_CADDIE = $7,
    ITEM_TYPE_CADDIE_ITEM = $8,
    ITEM_TYPE_SETITEM = $9,
    ITEM_TYPE_SKIN = $E,
    ITEM_TYPE_MASCOT = $10,
    ITEM_TYPE_CARD = $1F,
    ITEM_TYPE_AUX = $1C
  );

  TPLAYER_ACTION_SUB = (
      PLAYER_ACTION_SUB_STAND = $00,
      PLAYER_ACTION_SUB_SIT = $01,
      PLAYER_ACTION_SUB_SLEEP = $02
    );

  TPLAYER_ACTION_SUB_HEADER = (
      PLAYER_ACTION_HEADER_SCRATCHCARD = $0A
    );

  TGAME_TYPE = (
      VERSUS_STROKE = $00,
      VERSUS_MATCH = $01,
      CHAT_ROOM = $02,
      GAME_TYPE_03 = $03,
      TOURNEY = $04, // 30 Players tournament
      TOURNEY_TEAM = $05, // 30 Players team tournament
      TOURNEY_GUILD = $06, // Guild battle
      PANG_BATTLE = $07, // Pang Battle
      GAME_TYPE_08 = $08, // Public My Room
      GAME_TYPE_09 = $09,
      GAME_TYPE_0A = $0A,
      GAME_TYPE_0B = $0B,
      GAME_TYPE_0C = $0C,
      GAME_TYPE_0D = $0D,
      CHIP_IN_PRACTICE = $0E,
      GAME_TYPE_0F = $0F, // Playing for the first time
      GAME_TYPE_10 = $10, // Learn with caddie
      GAME_TYPE_11 = $11, // Stroke
      SSC = $12, // This is Chaos!
      HOLE_REPEAT = $13, // This is Chaos!
      GRANDPRIX = $14 // Grand Prix
  );

  TGAME_MODE = (
    GAME_MODE_FRONT = $00,
    GAME_MODE_BACK = $01,
    GAME_MODE_RANDOM = $02,
    GAME_MODE_SHUFFLE = $03,
    GAME_MODE_REPEAT = $04,
    GAME_MODE_SSC = $05
  );

  TGAMEPACKET = (
    PLAYER_LOGIN = $0002,
    PLAYER_CHAT = $0003,
    PLAYER_SELECT_LOBBY = $0004,

    PLAYER_CREATE_GAME = $0008,
    PLAYER_JOIN_GAME = $0009,

    PLAYER_CHANGE_NICKNAME = $0038,
    PLAYER_JOIN_MULTIGAME_LIST = $0081,
    PLAYER_LEAVE_MULTIGAME_LIST = $0082,
    PLAYER_JOIN_MULTIGAME_GRANDPRIX = $0176,
    PLAYER_LEAVE_MULTIGAME_GRANDPRIX = $0177,
    PLAYER_ENTER_GRANDPRIX = $0179,
    PLAYER_OPEN_PAPEL = $0098,
    PLAYER_OPEN_NORMAL_BONGDARI = $014B,
    PLAYER_OPEN_BIG_BONGDARI = $0186,
    PLAYER_SAVE_MACRO = $0069,
    PLAYER_OPEN_MAILBOX = $0143,
    PLAYER_READ_MAIL = $0144,
    PLAYER_RELEASE_MAILITEM = $0146,
    PLAYER_DELETE_MAIL = $0147,
    PLAYER_GM_COMMAND = $008F,
    {GAME PROCESS}
    PLAYER_USE_ITEM = $0017,
    PLAYER_PRESS_READY = $000D,
    PLAYER_START_GAME = $000E,
    PLAYER_LEAVE_GAME = $000F,
    PLAYER_LOAD_OK = $0011,
    PLAYER_SHOT_DATA = $001B,
    PLAYER_ENTER_TO_ROOM = $00EB, {MAY BE USE FOR CHAT ROOM ONLY}
    PLAYER_ACTION = $0063,
    PLAYER_CLOSE_SHOP = $0075,
    PLAYER_EDIT_SHOP = $0076,
    PLAYER_MASTER_KICK_PLAYER = $0026,
    PLAYER_CHANGE_GAME_OPTION = $000A,
    PLAYER_LEAVE_GRANDPRIX = $017A,
    PLAYER_AFTER_UPLOAD_UCC = $00B9,
    PLAYER_REQUEST_UPLOAD_KEY = $00C9,
    PLAYER_1ST_SHOT_READY = $0034,
    PLAYER_LOADING_INFO = $0048,
    PLAYER_GAME_ROTATE = $0013,
    PLAYER_CHANGE_CLUB = $0016,
    PLAYER_GAME_MARK = $012E,
    PLAYER_ACTION_SHOT = $0012,
    PLAYER_SHOT_SYNC = $001C,
    PLAYER_HOLE_INFORMATIONS = $001A,
    PLAYER_MY_TURN = $0022,
    PLAYER_HOLE_COMPLETE = $0031,
    PLAYER_CHAT_ICON = $0018,
    PLAYER_SLEEP_ICON = $0032,
    PLAYER_MATCH_DATA = $012F,
    PLAYER_MOVE_BAR = $0014,
    PLAYER_PAUSE_GAME = $0030,
    PLAYER_QUIT_SINGLE_PLAYER = $0130,
    PLAYER_CALL_ASSIST_PUTTING = $0185,
    PLAYER_USE_TIMEBOOSTER = $0065,
    PLAYER_DROP_BALL = $0019,
    PLAYER_CHANGE_TEAM = $0010,
    PLAYER_VERSUS_TEAM_SCORE = $0035,
    PLAYER_POWER_SHOT = $0015,
    PLAYER_WIND_CHANGE = $0141,
    PLAYER_SEND_GAMERESULT = $0006,

    {ITEM SPECIAL}
    PLAYER_REQUEST_ANIMALHAND_EFFECT = $015C,

    PLAYER_BUY_ITEM_GAME = $001D,
    PLAYER_ENTER_TO_SHOP = $0140,
    PLAYER_CHECK_USER_FOR_GIFT = $0007,

    PLAYER_SAVE_BAR = $000B,
    PLAYER_CHANGE_EQUIPMENT = $000C,
    PLAYER_CHANGE_EQUIPMENTS = $0020,

    PLAYER_WHISPER = $002A,
    PLAYER_REQUEST_TIME = $005C,
    PLAYER_GM_DESTROY_ROOM = $0060,
    PLAYER_GM_KICK_USER = $0061,
    PLAYER_REQUEST_LOBBY_INFO = $0043,
    PLAYER_REMOVE_ITEM = $0064,
    PLAYER_PLAY_AZTEC_BOX = $00EC,
    PLAYER_OPEN_BOX = $00EF,
    PLAYER_CHANGE_SERVER = $0119,
    PLAYER_ASSIST_CONTROL = $0184,
    PLAYER_SELECT_LOBBY_WITH_ENTER_CHANNEL = $0083,
    PLAYER_REQUEST_GAMEINFO = $002D,
    PLAYER_GM_SEND_NOTICE = $0057,
    PLAYER_REQUEST_PLAYERINFO = $002F,
    PLAYER_CHANGE_MASCOT_MESSAGE = $0073,
    PLAYER_ENTER_ROOM = $00B5,
    PLAYER_ENTER_ROOM_GETINFO = $00B7,

    PLAYER_OPENUP_SCRATCHCARD = $012A,
    PLAYER_PLAY_SCRATCHCARD = $0070,


    PLAYER_FIRST_SET_LOCKER = $00D0,
    PLAYER_ENTER_TO_LOCKER = $00D3,
    PLAYER_OPEN_LOCKER = $00CC,
    PLAYER_CHANGE_LOCKERPWD = $00D1,
    PLAYER_GET_LOCKERPANG = $00D5,
    PLAYER_LOCKERPANG_CONTROL = $00D4,
    PLAYER_CALL_LOCKERITEMLIST = $00CD,
    PLAYER_PUT_ITEMLOCKER = $00CE,
    PLAYER_TAKE_ITEMLOCKER = $00CF,

    // CLUB
    PLAYER_UPGRADE_CLUB = $0164,
    PLAYER_UPGRADE_ACCEPT = $0165,
    PLAYER_UPGRADE_CALCEL = $0166,
    PLAYER_UPGRADE_RANK = $0167,
    PLAYER_TRASAFER_CLUBPOINT = $016C,
    PLAYER_CLUBSET_ABBOT = $016B,
    PLAYER_CLUBSET_POWER = $016D,
    PLAYER_CHANGE_INTRO = $0106,
    PLAYER_CHANGE_NOTICE = $0105,
    PLAYER_CHANGE_SELFINTRO = $0111,
    PLAYER_LEAVE_GUILD = $0113,
    PLAYER_UPGRADE_CLUB_SLOT = $004B,

    // GUILD SYSTEM
    PLAYER_CALL_GUILD_LIST = $0108,
    PLAYER_SEARCH_GUILD = $0109,
    PLAYER_GUILD_AVAIABLE = $0102,
    PLAYER_CREATE_GUILD = $0101,
    PLAYER_REQUEST_GUILDDATA = $0104,
    PLAYER_GUILD_GET_PLAYER = $0112,
    PLAYER_GUILD_LOG = $010A,
    PLAYER_JOIN_GUILD = $010C,
    PLAYER_CANCEL_JOIN_GUILD = $010D,
    PLAYER_GUILD_ACCEPT = $010E,
    PLAYER_GUILD_KICK = $0114,
    PLAYER_GUILD_PROMOTE = $0110,
    PLAYER_GUILD_DESTROY = $0107,
    PLAYER_GUILD_CALL_UPLOAD = $0115,
    PLAYER_GUILD_CALL_AFTER_UPLOAD = $0116,

    // DIALY LOGIN
    PLAYER_REQUEST_CHECK_DAILY_ITEM = $016E,
    PLAYER_REQUEST_ITEM_DAILY = $016F,

    // ACHIEVEMENT
    PLAYER_CALL_ACHIEVEMENT = $0157,

    // Tiki Report
    PLAYER_OPEN_TIKIREPORT = $00AB,

    // UNKNOWN YET
    PLAYER_REQUEST_UNKNOWN = $00C1,

    // Memorial
    PLAYER_MEMORIAL = $017F,

    // Card Pack Open
    PLAYER_OPEN_CARD = $00CA,
    PLAYER_CARD_SPECIAL = $00BD,

    PLAYER_CALL_CUTIN = $00E5,

    // Magic Box
    PLAYER_DO_MAGICBOX = $0158,

    // RENT ITEM
    PLAYER_RENEW_RENT = $00E6,
    PLAYER_DELETE_RENT = $00E7,

    // QUEST
    PLAYER_LOAD_QUEST = $0151,
    PLAYER_ACCEPT_QUEST = $0152,

    // CARD INSERT
    PLAYER_PUT_CARD = $018A,
    PLAYER_PUT_BONUS_CARD = $018B,
    PLAYER_REMOVE_CARD = $018C,

    PLAYER_MATCH_HISTORY = $009C,

    // TOP NOTICE
    PLAYER_SEND_TOP_NOTICE = $0066,
    PLAYER_CHECK_NOTICE_COOKIE = $0067,

    PLAYER_UPGRADE_STATUS = $0188,
    PLAYER_DOWNGRADE_STATUS = $0189
  );

  ECLUBTYPE = (
    TYPE_BALANCE = $0,
    TYPE_POWER = $1,
    TYPE_CONTROL = $2,
    TYPE_SPIN = $3,
    TYPE_SPECIAL = $4
  );

  tCARDTYPE = (
    tNormal = $0,
    tCaddie = $40,
    tNPC = $41,
    tSpecial = $80
  );

  gCharType = (
    bTypeID,
    bIndex
  );

  TGameShift = (
    SHIFT_NAME = $0,
    SHIFT_PWD = $1,
    SHIFT_STROK = $2,
    SHIFT_MAP = $3,
    SHIFT_NUMHOLE = $4,
    SHIFT_MODE = $5,
    SHIFT_VSTIME = $6,
    SHIFT_MAXPLAYER = $7,
    SHIFT_MATCHTIME = $8,
    SHIFT_IDLE = $9,
    SHIFT_NATURAL = $E,
    SHIFT_HOLENUM = $B,
    SHIFT_HOLELOCK = $C
  );

  TShotType = (
    sUnknown = $1,
    sNormal = $2,
    sOB = $3,
    sSuccess = $4
  );

procedure SetMultiplierExp(Total: UInt8);

implementation

procedure SetMultiplierExp(Total: UInt8);
begin
  MultiplierExp := Total;
end;

end.
